pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r * .public
    - mv .public public
  artifacts:
    paths:
      - public/
      - public/domainvoider
      - public/ivoid
      - public/mirror
      - public/privacy
  only:
    - master