[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"

  [headers.values]
    X-Frame-Options = "DENY"
    Cache-Contol = "max-age=5, stale-while-revalidate=360, stale-if-error=360"
    X-XSS-Protection = "0"
    Content-Security-Policy = "base-uri 'self';connect-src 'self';default-src 'none';font-src 'self';form-action 'none';frame-ancestors 'none';frame-src 'none';img-src https://cdn.iosprivacy.com:443 'self';manifest-src 'self';media-src 'none';object-src 'none';script-src 'self';script-src-attr 'none';script-src-elem 'self';style-src 'self';style-src-attr 'none';style-src-elem 'self';upgrade-insecure-requests;worker-src 'self'"
    Permissions-Policy = "geolocation=(), camera=(), microphone=(), speaker=(), usb=(), xr=()"
    Referrer-Policy = "no-referrer"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-DNS-Prefetch-Control = "off"
    Clear-Site-Data = '"*"'
    Referrer-Policy = "no-referrer",
    Expect-CT = "enforce, max-age=86400"
