!#if adguard_app_android
!
! EXPMERIMENTAL !
!
129.134.30.12$network
157.240.22.19$network
31.13.66.35$network
31.13.70.7$network
31.13.71.1$network
31.13.80.36$network
31.13.80.8$network
!
||fbcdn.*/*$app=com.facebook.katana
||facebook.*/*$app=com.facebook.katana
||fbcdn.*/*$app=com.facebook.lite
||facebook.*/*$app=com.facebook.lite
||fbcdn.*/*$app=com.facebook.mlite
||facebook.*/*$app=com.facebook.mlite
||fbcdn.*/*$app=com.facebook.orca
||facebook.*/*$app=com.facebook.orca
!
||facebook.*/*$important,domain=facebook.*^|messenger.*^
||facebook.*/*$important,third-party
||fbcdn.*/*$important,domain=facebook.*^|messenger.*^
||fbcdn.*/*$important,third-party
!
||lite.facebook.*/*$important
||m.facebook.*/*$important
||c10r.facebook.*/*$important
||www.facebook.*/*$important
||messenger.*/*$important
!
||ns.facebook.com^$important
||dns.facebook.com^$important
!
*$script,important,domain=facebook.*^|messenger.*^
*$stylesheet,important,domain=facebook.*^|messenger.*^
*$xmlhttprequest,important,domain=facebook.*^|messenger.*^
!
||facebook.*/*$empty,important
||messenger.*/*$empty,important
!
!#endif