!#if adguard_app_android
!
129.134.30.12$network,important
157.240.22.19$network,important
31.13.66.35$network,important
31.13.70.7$network,important
31.13.71.1$network,important
31.13.80.36$network,important
31.13.80.8$network,important
!
*$app=com.facebook.katana,important
*$app=com.facebook.lite,important
*$app=com.facebook.mlite,important
*$app=com.facebook.orca,important
!
||connect.facebook.net^$important,domain=facebook.com
||connect.facebook.net^$important,third-party
||scontent.xx.fbcdn.net^$important,domain=facebook.com
||scontent.xx.fbcdn.net^$important,third-party
!
||api.facebook.com^$important,domain=facebook.com
||api.facebook.com^$important,third-party
||graph.facebook.com^$important,domain=facebook.com
||graph.facebook.com^$important,third-party
||star.c10r.facebook.com^$important,domain=facebook.com
||star.c10r.facebook.com^$important,third-party
!
||lite.facebook.com^$important
||m.facebook.com^$important
||star-mini.c10r.facebook.com^$important
||www.facebook.com^$important
!
||a.ns.facebook.com^$important,domain=facebook.com
||a.ns.facebook.com^$important,third-party
||dns.facebook.com^$important,domain=facebook.com
||dns.facebook.com^$important,third-party
!
||fbcdn.net^$important,domain=facebook.com
||fbcdn.net^$important,third-party
!
||facebook.com^$empty,important
!
!#endif