name: prototype-pull-request

on:
  schedule:
    # Once a year, the 2nd of January
    - cron: 0 0 2 1 *
    # Weekly on Sunday
    # 0 0 * * 0


jobs:
  GenerateSourcecred:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v1
    - name: Cache SourceCred Data
      id: cache-data
      uses: actions/cache@v1
      with:
        path: sourcecred_data
        key: ${{ runner.os }}-sourcecred_data
    - name: Cache Static Files
      id: cache-static
      uses: actions/cache@v1
      with:
        path: docs
        key: ${{ runner.os }}-sourcred_docs
    - name: Generate SourceCred Prototype
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        mkdir -p sourcecred_data docs;
        SOURCECRED_GITHUB_TOKEN=${TOKEN} docker run -i --rm -v $PWD/sourcecred_data:/data -e SOURCECRED_GITHUB_TOKEN sourcecred/sourcecred:dev load ${GITHUB_REPOSITORY}
        docker run -i --rm -v $PWD/sourcecred_data:/data -v $PWD/docs:/output sourcecred/sourcecred:dev build --output-path /output
        mkdir -p docs/api/v1/
        cp -r sourcecred_data/ docs/api/v1/data
        rm -rf docs/api/v1/data/cache
    - name: Open Pull Request
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH_AGAINST: "master"
      run: |
        printf "GitHub Actor: ${GITHUB_ACTOR}\n"
        git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        git branch

        export BRANCH_FROM="update/sourcecred-prototype-$(date '+%Y-%m-%d')"
        git checkout -b "${BRANCH_FROM}"
        git branch

        git config --global user.name "github-actions"
        git config --global user.email "github-actions@users.noreply.github.com"

        git add docs/*

        if git diff-index --quiet HEAD --; then
           printf "No changes\n"
        else
           printf "Changes\n"
           git commit -m "Automated deployment to update docs/ static files $(date '+%Y-%m-%d')"
           git push origin "${BRANCH_FROM}"

           # Absolutely must download specific sha of script
           wget https://raw.githubusercontent.com/${GITHUB_REPOSITORY}/9e1f0644a2398f8c99b8b19fd685566fce207959/.github/workflows/pull_request.sh
           chmod +x pull_request.sh
           TITLE="Updating SourceCred Prototype" /bin/bash -e pull_request.sh
        fi
